### ISSUE TITLE
Vite: Uncaught ReferenceError: process is not defined 

### ISSUE THREAD

**Issue by pandec** [sushinpv/react-secure-storage#25]
Hi! I'm trying to use the package with Vite + React but got the error that `process` is undefined...

Looks like Vite is using `import.meta.env` instead of `process.env` now ([link](https://vitejs.dev/guide/env-and-mode.html))

Any chance this could be configured somehow? 

```
envHelper.js:20 Uncaught ReferenceError: process is not defined`
    at Object.getEnvValue2 [as getEnvValue] (envHelper.js:20:3)
    at getSecurePrefix2 (utils.js:17:39)
    at node_modules/react-secure-storage/dist/localStorageHelpers.js (localStorageHelpers.js:26:29)
    at __require2 (chunk-HYZYPRER.js?v=9e3c2685:15:50)
    at node_modules/react-secure-storage/dist/index.js (index.js:10:51)
    at __require2 (chunk-HYZYPRER.js?v=9e3c2685:15:50)
    at index.js:121:19
getEnvValue2 @ envHelper.js:20
getSecurePrefix2 @ utils.js:17
node_modules/react-secure-storage/dist/localStorageHelpers.js @ localStorageHelpers.js:26
__require2 @ chunk-HYZYPRER.js?v=9e3c2685:15
node_modules/react-secure-storage/dist/index.js @ index.js:10
__require2 @ chunk-HYZYPRER.js?v=9e3c2685:15
(anonymous) @ index.js:121
Show 5 more frames
```

**Comment by sushinpv** [comment]
Hi @pandec , 

Please have a look at this answer which is discussed on our couple of discussions 

https://github.com/sushinpv/react-secure-storage/discussions/24
