### ISSUE TITLE
why i got process is not defined

### ISSUE THREAD

**Issue by nurwanto18** [sushinpv/react-secure-storage#4]
main.js:113158 Uncaught ReferenceError: process is not defined
    at getFingerprint (main.js:113158:8)
    at new EncryptionService (main.js:113088:47)
    at getAllLocalStorageItems (main.js:113579:19)
    at new SecureLocalStorage (main.js:113475:64)
    at ./node_modules/react-secure-storage/dist/index.js (main.js:113535:26)
    at __webpack_require__ (main.js:128421:33)
    at fn (main.js:128655:21)
    at ./src/pages/Login.js (main.js:37340:78)
    at __webpack_require__ (main.js:128421:33)
    at fn (main.js:128655:21)

**Comment by nurwanto18** [comment]
done, you must install react script below v5, v5 can give you error thanks
